
import Header from "@/components/Header";

const About = () => {
  return (
    <div className="min-h-screen">
      <Header />
      <div className="pt-32 pb-20 px-6 max-w-4xl mx-auto">
        <h1 className="text-4xl md:text-5xl font-bold mb-8 animate-slide-in-up">About Melody</h1>
        
        <div className="space-y-8">
          <section className="glass-panel p-8 animate-slide-in-up animation-delay-100">
            <h2 className="text-2xl font-bold mb-4">Our Mission</h2>
            <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
              Melody was created with a simple mission: to make professional music industry contracts accessible to everyone in the music business, from independent artists to established professionals.
            </p>
            <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
              We believe that legal protection shouldn't be a luxury or require extensive legal knowledge. By combining artificial intelligence with industry expertise, we've created a platform that generates clear, comprehensive, and legally sound music contracts in minutes.
            </p>
          </section>
          
          <section className="glass-panel p-8 animate-slide-in-up animation-delay-200">
            <h2 className="text-2xl font-bold mb-4">How It Works</h2>
            <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
              Our platform uses advanced natural language processing to understand your contract needs. Simply describe what you're looking for in plain English, and our AI will identify the appropriate contract type and ask for any necessary additional information.
            </p>
            <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
              Once you've provided the required details, we generate a customized contract that adheres to industry standards and best practices. You can review, edit, and download your contract in multiple formats.
            </p>
          </section>
          
          <section className="glass-panel p-8 animate-slide-in-up animation-delay-300">
            <h2 className="text-2xl font-bold mb-4">Legal Disclaimer</h2>
            <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
              While we strive to create contracts that meet industry standards, Melody is not a law firm and does not provide legal advice. The contracts generated by our platform are templates and may need to be reviewed by a qualified attorney, especially for complex situations or high-value agreements. We recommend consulting with a legal professional before signing any contract.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default About;
