// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsggkvchqqwstdmewpvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzZ2drdmNocXF3c3RkbWV3cHZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NzAxNzIsImV4cCI6MjA2MjM0NjE3Mn0.9vV31IK-X8eToi6pBG6lsjIquS27IDt6OvzEn_04c4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});